Repository valescamoura/chess, pull requests merged in 2022-06, with the labels that each got.

#42 Added the min-max IA algorithm
  chess/src/board.py
  chess/src/cli.py
  chess/src/ia.py
  chess/src/ia_fight.py
Labels: team:ia

#43 Added the Alpha–beta pruning
  chess/src/board.py
  chess/src/cli.py
  chess/src/ia.py
  chess/src/ia_fight.py
Labels: team:ia

#45 bugfix
  chess/src/board.py
  chess/src/test.py
Labels: bug

#50 Alpha-Betha prunning improvements
  chess/src/ia.py
  chess/src/ia_fight.py
Labels: team:ia

#52 Bugfix
  chess/src/board.py
Labels: team:back

#60 Bug fix services
  chess/src/services.py
Labels: bug, team:back

#62 Mudança na classe e criação de novo método para IA
  chess/src/services.py
  tests/test_services.py
Labels: bug, team:back

#67 Atualização método execute_move
  chess/src/services.py
Labels: bug

#68 Added the unitary IA tests
  tests/test_ia.py
Labels: team:ia, team:tests
