Repository valescamoura/chess, pull requests merged in 2022-04, with the labels that each got.

#2 Initial Setting
  README.md
  chess/__init__.py
  chess/asgi.py
  chess/settings.py
  chess/urls.py
  chess/wsgi.py
  manage.py
  requirements.txt
Labels: documentation, time:back

#6 Criando workflow django
  .github/workflows/django.yml
  build.sh
  chess/settings.py
Labels: team:back

#14 Correção do readme
  README.md
Labels: documentation

#15 Implemented game rules
  chess/chess.py
  chess/cli.py
Labels: team:back

#18 Added board scores.
  chess/chess.py
  chess/cli.py
Labels: team:back, team:ia

#19 Adicionado o módulo multipledispatch ao requirements.txt
  requirements.txt
Labels: bug, team:back

#16 Criação da versão aleatória da IA
  chess/cli.py
  chess/ia.py
Labels: team:ia

#32 Bugfix
  chess/cli.py
  chess/src/IA/ia.py
  chess/src/board.py
  chess/src/cli.py
  chess/src/ia.py
  chess/src/ia_fight.py
  chess/src/test.py
Labels: team:back, team:ia
